version: "3.9" 
services:
  server:
    build: 
      context: src  
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/neb-backup:minecraft
    hostname: "neb-backup"  
    container_name: "neb-backup"  
    # restart: "always"
    networks:
    - "minecraft"
    environment:
      NEB_BACKUP_TYPE: restic
      NEB_BACKUP_NAME: "neb-backup"
      NEB_BACKUP_DELAY: 10s
      NEB_BACKUP_INTERVAL: 30s    
      NEB_BACKUP_RETENTION: 1h  
      NEB_BACKUP_EXCLUDES: "*.jar,cache,logs,crash-reports"
      RESTIC_REPOSITORY: "/usr/local/backup"
      RESTIC_PASSWORD: test
      RCON_HOST: localhost
      RCON_PASSWORD: testing
    volumes:
      - "${PWD}/data:/usr/local/data"      
      - "${PWD}/backup:/usr/local/backup"
networks:
  minecraft:
    external:
        name: neb-mc-server_internal
